---

- hosts: all
  become: true
  tasks:
    - name: update packages
      yum:
        name: '*'
        state: latest
        update_only: true

    - name: install yum packages
      yum:
        name:
          - docker
          - device-mapper-persistent-data
          - lvm2
          - python-pip
        state: present
      notify:
          - add user
          - start docker

  handlers:
    - name: add user
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: start docker
      service:
        name: docker.service
        enabled: True
        state: started
